  name: Fetch Data to File
  on:
    workflow_dispatch:
    schedule:
      - cron: "*/5 * * * *"
  jobs:
    refresh-feed:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Fetch JSON Data
        id: fetchdata
        run: |
          curl -o warStatus.json https://api.live.prod.thehelldiversgame.com/api/WarSeason/801/Status
          
      - name: Commit and Push if Changed
        run: |
          git add warStatus.json
          git commit -m "Update War Status JSON data" || echo "No changes to commit"
          git push
